# ===================================
# 🖤 КОНФИГУРАЦИЯ ТЕМНОГО ПОВЕЛИТЕЛЯ 🖤
# ===================================
# Автор: BedePay
# Версия: 2.0 (Оптимизированная)

# ===================================
# ⚔️ ОСНОВНЫЕ НАСТРОЙКИ БОССА
# ===================================
boss:
  # Система сложности (1-5)
  # 1 = Легко (для новичков) | 3 = Нормально | 5 = Экстрим (для профи)
  difficulty_level: 3
  
  # Здоровье босса по фазам (базовые значения)
  health:
    phase_1: 2000
    phase_2: 1600  
    phase_3: 1200
  
  # Кулдауны способностей (в секундах)
  abilities:
    fireball: 5          # Огненные шары
    summon_minions: 8    # Призыв миньонов
    pull_players: 12     # Притягивание игроков
    teleport: 10         # Телепортация
    magic_missiles: 3    # Магические снаряды
    earth_spikes: 7      # Земляные шипы
    meteor_storm: 15     # Метеоритный дождь
    blinding_flash: 9    # Ослепляющая вспышка
    soul_scream: 11      # Крик души
  
  # Ограничения поведения
  movement_limits:
    max_flight_height: 20        # Максимальная высота полёта
    max_distance_from_spawn: 100 # Максимальное расстояние от спауна
  
  # Правила атак по игровым режимам
  attack_rules:
    spectators: false    # Атаковать наблюдателей
    creative: false      # Атаковать в творческом режиме
    vanished: false      # Атаковать невидимых игроков
  
  # Боссбар
  bossbar:
    show_all_gamemodes: true  # Показывать всем режимам игры

# ===================================
# 🎁 СИСТЕМА НАГРАД
# ===================================
rewards:
  # Осколки Темного Повелителя
  fragments:
    base_amount: [1, 3]           # [минимум, максимум]
    extra_chance: 30              # Шанс дополнительных осколков (%)
    extra_amount: [1, 2]          # [мин, макс] дополнительных
    
    # Бонус за групповую игру
    team_bonus:
      enabled: true
      radius: 60                  # Радиус поиска игроков
      bonus_per_player: 5         # Процент бонуса за игрока
      max_players: 10             # Максимум игроков для бонуса
  
  # Редкие предметы (шанс в процентах)
  rare_items:
    unbreakable_elytra: 13      # Неломающиеся крылья
    enhanced_sword: 13          # Усиленный меч
    teleport_staff: 13          # Посох телепортации
    shadow_boots: 13           # Сапоги теней
    power_crystal: 13            # Кристалл силы
  
  # Яйца мобов
  mob_eggs:
    enabled: true
    chance: 20                  # Общий шанс выпадения
    amount: [1, 3]              # [минимум, максимум]

# ===================================
# 🛡️ БРОНЯ ТЕМНОГО ПОВЕЛИТЕЛЯ
# ===================================
armor:
  # Стоимость крафта (в осколках)
  craft_cost:
    helmet: 6
    chestplate: 8
    leggings: 7
    boots: 4
  
  # Эффекты полного комплекта
  full_set_effects:
    damage_resistance: 3        # Уровень защиты
    fire_resistance: true       # Огнестойкость
    water_breathing: true       # Подводное дыхание
    speed: 2                    # Скорость
    strength: 1                 # Сила
    regeneration: 1             # Регенерация
    night_vision: true          # Ночное зрение
  
  # Специальные способности брони
  special_abilities:
    lightning_strike_chance: 15     # Шанс удара молнии при атаке (%)
    teleport_on_damage_chance: 20   # Шанс телепорта при уроне (%)
    area_damage: 4.0                # Урон по области
    boots_depth_strider: true       # Подводная ходьба на сапогах

# ===================================
# ⚡ УНИКАЛЬНЫЕ ПРЕДМЕТЫ
# ===================================
unique_items:
  # Посох телепортации
  teleport_staff:
    cooldown: 35          # Кулдаун в секундах
    distance: 20          # Дистанция телепортации
  
  # Клинок разрушения
  enhanced_sword:
    pull_cooldown: 30     # Кулдаун притягивания
    pull_distance: 10     # Дистанция притягивания
    pull_strength: 3.0    # Сила притягивания
  
  # Сапоги теней
  shadow_boots:
    invisibility_delay: 2  # Задержка невидимости (секунды)
  
  # Крылья тьмы
  dark_elytra:
    firework_interval: 5   # Интервал фейерверков (секунды)
    repair_interval: 3     # Интервал починки (секунды)
    repair_amount: 50      # Количество восстанавливаемой прочности
    max_speed: 3.0         # Максимальная скорость полёта

# ===================================
# 🌍 АВТОМАТИЧЕСКИЕ СОБЫТИЯ
# ===================================
events:
  enabled: true
  
  # Расписание спавна
  schedule:
    interval_hours: [2, 4]        # [минимум, максимум] часов между спавнами
    allowed_time: [8, 22]         # [с, до] часов дня для спавна
    min_players_online: 3         # Минимум игроков онлайн
  
  # Локации спавна
  spawn_locations:
    allowed_worlds: ["world", "world_nether"]
    search_radius: 1000           # Радиус поиска места
    distance_from_players: [50, 300]  # [мин, макс] расстояние от игроков
    spawn_height: [50, 150]       # [мин, макс] высота спавна
  
  # Удаление босса
  removal:
    inactive_timeout: 30          # Минут без игроков поблизости
    check_radius: 100             # Радиус проверки игроков
    warning_time: 5               # Предупреждение за N минут
  
  # Уведомления
  notifications:
    spawn_announcement: true      # Объявление о спавне
    periodic_reminders: true      # Периодические напоминания
    reminder_interval: 5          # Интервал напоминаний (минуты)
    max_reminders: 6              # Максимум напоминаний
    local_radius: 200             # Радиус локальных уведомлений

# ===================================
# 🎨 ВИЗУАЛЬНЫЕ ЭФФЕКТЫ
# ===================================
effects:
  particles_multiplier: 0.5     # Множитель частиц (0.5 = вдвое меньше)
  ambient_effects: true         # Постоянные эффекты вокруг босса
  phase_transition_effects: true # Эффекты смены фаз
  death_effects: true           # Эффекты смерти
  
  # Анимация смерти
  death_animation:
    enabled: true
    duration: 8               # Длительность в секундах

# ===================================
# 💬 ПРОВОКАЦИИ БОССА
# ===================================
chat_taunts:
  enabled: true
  interval: 45                  # Интервал в секундах
  chance: 60                    # Шанс отправки (%)
  radius: 50                    # Радиус поиска игроков

# ===================================
# 📊 НАСТРОЙКИ СЛОЖНОСТИ
# ===================================
difficulty_settings:
  # Уровень 1 - Легкий
  level_1:
    name: "Легкий"
    health_multiplier: 0.5
    damage_multiplier: 0.6
    abilities_speed: 0.7
    drops_multiplier: 0.8
    minions_multiplier: 0.5
  
  # Уровень 2 - Простой
  level_2:
    name: "Простой"
    health_multiplier: 0.75
    damage_multiplier: 0.8
    abilities_speed: 0.85
    drops_multiplier: 0.9
    minions_multiplier: 0.7
  
  # Уровень 3 - Нормальный (базовый)
  level_3:
    name: "Нормальный"
    health_multiplier: 1.0
    damage_multiplier: 1.0
    abilities_speed: 1.0
    drops_multiplier: 1.0
    minions_multiplier: 1.0
  
  # Уровень 4 - Сложный
  level_4:
    name: "Сложный"
    health_multiplier: 1.5
    damage_multiplier: 1.3
    abilities_speed: 1.2
    drops_multiplier: 1.2
    minions_multiplier: 1.5
    additional_effects: true
  
  # Уровень 5 - Экстремальный
  level_5:
    name: "Экстремальный"
    health_multiplier: 4.0
    damage_multiplier: 1.8
    abilities_speed: 1.6
    drops_multiplier: 2.0
    minions_multiplier: 2.5
    additional_effects: true
    boss_regeneration: false
    enhanced_ai: true
    unique_abilities: true

# ===================================
# 💬 СООБЩЕНИЯ
# ===================================
messages:
  # Сообщения босса
  boss:
    spawn_title: "&4💀 ТЕМНЫЙ ПОВЕЛИТЕЛЬ! 💀"
    spawn_subtitle: "&cПриготовьтесь к битве!"
    death_title: "&6🎉 БОСС ПОВЕРЖЕН! 🎉"
    death_subtitle: "&aВеликая награда ждет героев!"
    
    # Фазы
    phase_2_title: "&5⚡ ФАЗА 2 ⚡"
    phase_2_subtitle: "&cМагическая ярость!"
    phase_3_title: "&4💀 ФИНАЛЬНАЯ ФАЗА! 💀"
    phase_3_subtitle: "&6Последняя битва!"
  
  # Сообщения брони
  armor:
    full_set_equipped: "&5⚡ Сила Темного Повелителя! ⚡"
    lightning_strike: "&e⚡ Молния поражает врага! ⚡"
    teleport_escape: "&d🌀 Телепорт в безопасность! 🌀"
    area_damage: "&4💥 Темная энергия поражает! 💥"
  
  # Система наград
  rewards:
    fragment_obtained: "&5🖤 Вы получили Осколок Темного Повелителя! 🖤"
    rare_drop: "&6✨ Редкий предмет выпал с босса! ✨"
  
  # Крафт
  crafting:
    success: "&a✅ Вы успешно создали %item%!"
    insufficient_fragments: "&c❌ Недостаточно осколков! Нужно %required%, у вас: %current%"
    fragments_protection: "&c❌ Осколки Темного Повелителя можно использовать только для крафта его брони!"
  
  # Команды
  commands:
    boss_already_active: "&cБосс уже активен! Сначала победите текущего босса."
    boss_not_active: "&eВ данный момент босс не активен."
    boss_summoned: "&aТемный Повелитель вызван!"
    boss_killed: "&a✅ Темный Повелитель мгновенно уничтожен!"
    no_permission: "&cУ вас нет прав для использования этой команды!"
    player_only: "&cЭту команду может использовать только игрок!"
  
  # События
  events:
    spawn_global: "&4☄ ВНИМАНИЕ! ☄ &6Темный Повелитель пробудился в мире &e%world%&6!"
    spawn_coordinates: "&6📍 Примерные координаты: &e%x%, %y%, %z% &7(±200 блоков)"
    spawn_warning: "&c⚠ Босс исчезнет через %time% минут без активности!"
    reminder_title: "&4💀 БОСС ВСЕ ЕЩЕ ЖИВ! 💀"
    reminder_subtitle: "&6Поторопитесь!"
    removal_warning: "&c🚨 ПОСЛЕДНЕЕ ПРЕДУПРЕЖДЕНИЕ! 🚨"
    removal_final: "&4💀 Повелитель растворился в тенях... 💀"
  
  # Провокации босса
  taunts:
    general:
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cНикто не сможет остановить меня!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cЯ чувствую запах вашего страха..."
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cВы все погибнете от моих рук!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cТьма поглотит этот мир!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cВаши жалкие попытки меня забавляют!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cВаше время истекло, смертные!"
    
    targeted:
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &c%player%, ты куда убегаешь, трус?!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &c%player%, иди ко мне! Я тебя жду!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cНе прячься, %player%! Смерть все равно найдет тебя!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &c%player%, твое оружие против меня бесполезно!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cЯ вижу тебя, %player%! Тебе некуда деваться!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &c%player%, ты думал спрятаться от темного повелителя?!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cТы слишком слаб, %player%! Сдавайся!"
    
    on_damage:
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cТы только разозлил меня, %attacker%!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cЭто все, на что ты способен, %attacker%?!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cТвоя атака лишь щекочет, %attacker%!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cЯ стану еще сильнее от твоего удара, %attacker%!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cТы пожалеешь об этом, %attacker%!"
    
    low_health:
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cВы только пробудили мой истинный гнев!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cТеперь я покажу вам настоящую силу тьмы!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cЭто еще не конец! Я не сдамся!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cМоя смерть будет вашим проклятием!"
      - "&4[ТЕМНЫЙ ПОВЕЛИТЕЛЬ] &cВ час моей смерти тьма поглотит вас всех!"

# ===================================
# 🔧 ТЕХНИЧЕСКИЕ НАСТРОЙКИ
# ===================================
technical:
  # Только для отладки (отключено в продакшене)
  debug_logging: false
  
  # CustomModelData для осколков (изменить для сброса старых)
  fragments_model_data: 77777
  
  # Версия конфига (не изменять)
  config_version: "2.0" 